# Generated by Django 5.2 on 2025-06-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_phone_number_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Название организации (для организаторов)', max_length=255, null=True),
        ),
    ]
