# Generated by Django 5.2 on 2025-06-16 11:33

import core.models
import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_task_deadline_task_deadline_date_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Фотоотчет', 'verbose_name_plural': 'Фотоотчеты'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='taskassignment',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Назначение задания', 'verbose_name_plural': 'Назначения заданий'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-rating', 'username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='volunteerproject',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Участие волонтера', 'verbose_name_plural': 'Участия волонтеров'},
        ),
        migrations.AddField(
            model_name='photo',
            name='feedback',
            field=models.TextField(blank=True, help_text='Комментарий организатора', null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='moderated_at',
            field=models.DateTimeField(blank=True, help_text='Дата модерации', null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Оценка от 1 до 5 звезд', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='project',
            name='volunteers',
            field=models.ManyToManyField(blank=True, help_text='Волонтеры проекта', related_name='projects', through='core.VolunteerProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='volunteers',
            field=models.ManyToManyField(blank=True, help_text='Волонтеры, выполняющие задание', related_name='tasks', through='core.TaskAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteerproject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно ли участие'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='Фотоотчет', upload_to=core.models.photo_upload_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(help_text='Проект', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.project'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], db_index=True, default='pending', help_text='Статус модерации', max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Связанное задание', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_photos', to='core.task'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='volunteer',
            field=models.ForeignKey(help_text='Волонтер', limit_choices_to={'is_organizer': False}, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(help_text='Город реализации проекта', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(help_text='Организатор проекта', limit_choices_to={'is_organizer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], db_index=True, default='pending', help_text='Статус модерации проекта', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Теги проекта', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Название проекта', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(help_text='Создатель задания', limit_choices_to={'is_organizer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, help_text='Дата дедлайна', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Время окончания', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='Проект', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Время начала', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('completed', 'Выполнена')], db_index=True, default='open', help_text='Статус задания', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, help_text='Изображение для задания', null=True, upload_to=core.models.task_image_upload_path),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(help_text='Текст задания'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='accepted',
            field=models.BooleanField(default=False, help_text='Принял ли волонтер задание'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='completed',
            field=models.BooleanField(default=False, help_text='Выполнено ли задание'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Дата выполнения', null=True),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='feedback',
            field=models.TextField(blank=True, help_text='Отзыв о выполнении', null=True),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Оценка выполнения', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='task',
            field=models.ForeignKey(help_text='Задание', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.task'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='volunteer',
            field=models.ForeignKey(help_text='Волонтер', limit_choices_to={'is_organizer': False}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=False, help_text='Является ли пользователь организатором'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0, help_text='Рейтинг пользователя от 0 до 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='volunteerproject',
            name='project',
            field=models.ForeignKey(help_text='Проект', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_projects', to='core.project'),
        ),
        migrations.AlterField(
            model_name='volunteerproject',
            name='volunteer',
            field=models.ForeignKey(help_text='Волонтер', limit_choices_to={'is_organizer': False}, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
